### ISSUE TITLE
Create an unmaintainable-code organization for updates or additions to article

### ISSUE THREAD

**Issue by Droogans** [Droogans/unmaintainable-code#19]
I'll need to clear it with the original author of this article first, but I imagine it should be ok to create a new organization, https://github.com/unmaintainable-code to house this repository, as well as new versions of it that are maintained by the community.

I'm not sure yet what the details are, but I do know that by creating a new organization, there can be a clear distinction between the original (altered for formatting reasons only) and derivative works, as well as allowing for additional contributors. My hope is that @RoedyGreen would be interested in participating in some capacity!

I'm starting to see more and more suggestions for new content in this article, such as #20, #18, #17, and #14. I am a big supporter of having some new ideas get brought to this article, but not at the original's expense.

**Comment by Droogans** [comment]
See here for more detail on why pull requests which add or remove original content from this article will never be accepted: https://github.com/Droogans/unmaintainable-code/blob/master/ABOUT.md#improvements-to-this-article.

**Comment by birbilis** [comment]
A fork would be better

**Comment by aditsachde** [comment]
Can we close this issue? Its not been acted upon in over a year and its annoying seeing a 1 next to issues.
