### ISSUE TITLE
words and longs are of different size in different systems

### ISSUE THREAD

**Issue by birbilis** [Droogans/unmaintainable-code#24]
> where the  w  values hint that they are words, but they really refer to longs. The real value of this approach comes clear with the Win64 migration, when the parameters will be 64 bits wide, but the old  w  and  l  prefixes will remain forever.

This is a bit misleading, since words and longs are of different size in different systems. From what I remember C spec was allowing (or even encouraging) this. There are other types used int32, uint32 (for unsigned) etc. for immutable-size types. 

This has to be considered when writing portable (between architectures/CPUs) code that assumes certain data structure offsets/sizes etc.

**Comment by Droogans** [comment]
I noticed you've raised an issue suggesting an alteration to the article. Please see #19 for more information as to why I'm not going to accept any of these types of issues _in this repository_.

I'm seeing plenty of interest in expanding this article with content from the larger community. I think soon there will be a place where you can suggest a change like this and from there a larger group of maintainers and contributors can weigh in on what gets merged into a community version of this article. For now though I'm afraid I'll need to close issues like this in the mean time.
