### ISSUE TITLE
Another thing

### ISSUE THREAD

**Issue by gabriel-jones** [Droogans/unmaintainable-code#25]
Swift lets you use emojis in your code as variable names, functions etc. which is basically impossible to read. I don't know if this is supported in other languages though...

**Comment by Droogans** [comment]
I noticed you've raised an issue suggesting an alteration to the article. Please see #19 for more information as to why I'm not going to accept any of these types of issues _in this repository_.

I'm seeing plenty of interest in expanding this article with content from the larger community. I think soon there will be a place where you can suggest a change like this and from there a larger group of maintainers and contributors can weigh in on what gets merged into a community version of this article. For now though I'm afraid I'll need to close issues like this in the mean time.
