### ISSUE TITLE
Quoted phrase in readme is not cited correctly

### ISSUE THREAD

**Issue by doodlebro** [Droogans/unmaintainable-code#29]
This is stupid, yet necessary

http://militaryhistorynow.com/2014/07/14/ten-famous-things-napoleon-never-actually-said/

and

https://en.wikipedia.org/wiki/Hanlon%27s_razor

The quote should be attributed to Robert J. Hanlon, Napoleon has enough accolades ;)

**Comment by Droogans** [comment]
Thanks for the clarification. I didn't know that.

However, I'm not looking to deviate from the original author's work, so if there's ever a change reflected in the original article, I'll change it here as well.
