### ISSUE TITLE
The article is under copyright

### ISSUE THREAD

**Issue by Caleb-An** [Droogans/unmaintainable-code#3]
See http://mindprod.com/jgloss/unmain.html,
exceptions seem to be made for only non-English translations.

**Comment by Droogans** [comment]
I have already emailed the author and asked permission to republish this on github specifically. I will take this down at any time should the author change their mind about their decision in the future.

Below is a transcription of our email exchange.

```
On 2015-07-25 3:29 AM, Andrew Yurisich wrote:
I'm in the process of converting your essay to markdown, specifically so that I can link to the various sections when suggesting to my team mates how they might best improve their code.

I thought it would make sense to ask for permission before I publicly copy your work and rerelease it on another platform besides your web site.

Do you mind if I do that?
```

```
On 2015-07-26 4:10 PM, Roedy Green <feedback@mindprod.com> wrote:

Please insert a link or mention the URL of the original.
```

**Comment by Droogans** [comment]
I do appreciate you looking out for the author though! If you have any contact with them and know first hand that they don't approve of this repository, please have them address it here and I'd be happy to take this down.
