### ISSUE TITLE
Napoleon attribution is incorrect

### ISSUE THREAD

**Issue by GLMeece** [Droogans/unmaintainable-code#34]
Please read [the Wiki article on Hanlon's razor](https://en.wikipedia.org/wiki/Hanlon%27s_razor). This quote has been consistently misattributed, although I must admit this is the first time _I_ personally have seen it attributed to Napoleon.

**Comment by Droogans** [comment]
Thank you for bringing this up! However, I am closing this as a duplicate of #29.
