### ISSUE TITLE
you are evil

### ISSUE THREAD

**Issue by NicTanghe** [Droogans/unmaintainable-code#36]
If annyone is smart enough to do this they can get a new job as an actually useful programmer instead of being an asshole.

**Comment by qwertychouskie** [comment]
@Drunkenpanda2000 It's just a joke, relax.

**Comment by Droogans** [comment]
I did want to point you at https://github.com/Droogans/unmaintainable-code/blob/master/ABOUT.md so you wouldn't feel like I was just closing this without addressing your concerns!

**Comment by wandadars** [comment]
@Drunkenpanda2000  Humor is a challenging topic for you, isn't it?
